### ISSUE TITLE
Connecting Hololens2 on USB disables PC wifi

### ISSUE THREAD

**Issue by eusebiu** [microsoft/NCM-Driver-for-Windows#10]
I have a Hololens2 and after the 21H1 update (on Hololens), when connecting the device on USB, the PC wifi is disabled automatically (Win10 1909). If I unplug the device, wifi connects normally.

How can I solve this (keep wifi active while Hololens2 is connected on USB)?

According to https://docs.microsoft.com/en-us/windows/mixed-reality/develop/platform-capabilities-and-apis/using-the-windows-device-portal this UsbNcm is default in Hololens2.

**Comment by brandonjiang** [comment]
Eusebiu, can you use Feedback Hub to open a report on this behavior that you observed? Feedback Hub app has a option to record traces while you are repeat the repro steps above, if you can include the repro traces it would be great.

**Comment by eusebiu** [comment]
I am trying to enable the Diagnostic data since that setting is managed by my organization IT department.
Isn't any other way to submit the report?

**Comment by brandonjiang** [comment]
Feedback Hub is the way for you to submit the report. Based on your description of issue above, the root cause could be somewhere else in the OS system, so having the report from Feedback Hub allows us to properly triage this issue and re-direct to right team.
