### ISSUE TITLE
safe removable required

### ISSUE THREAD

**Issue by yaoliqing** [microsoft/NCM-Driver-for-Windows#11]
does windows ncm driver let the ncm device in safe removeble required?

**Comment by brandonjiang** [comment]
WIndows NCM driver assumes the NCM device does not require safe removal

**Comment by yaoliqing** [comment]
But windows do put the ncm device in saf removeble required.

**Comment by yaoliqing** [comment]
> Windows NCM driver assumes the NCM device does not require safe removal

You can find that require safe removal is true in usb property tab, also find the ncm device in Safely Remove Hardware and Eject Media, like a U disk.
