### ISSUE TITLE
Missing header file

### ISSUE THREAD

**Issue by igorojas** [Microsoft/NCM-Driver-for-Windows#3]
I tried to build this NCM driver but preview/netringiterator.h is missing. Can anyone point to its location?

Thanks!
IgoR

**Comment by brandonjiang** [comment]
Igor

you need preview version of WDK, see [here](https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewWDK)

Thanks
Brandon

**Comment by morizzo** [comment]
Thank you for the info. Yes, preview version of WDF resolved the missing header file issue.
But the latest WDF, 10.0.18362.0 I have just downloaded, seems too new to build this driver. Many NetRing* functions are missing in the WDK version.
E.g. NetRingGetTxPostPacketFragmentIterator, NetRingIteratorAny and NetRingAdvanceFragmentIterator functions are not in the WDK.

What exactly version of WDK did you test this driver?
And can I get the same version?

Best,
Morizzo

**Comment by brandonjiang** [comment]
Morizzo,

Thanks for reporting this. the current NCM sources is a bit outdated. we'll release a new drop of NCM sources code soon, that will work with WDK 10.0.18362.0

Thanks
Brandon

**Comment by brandonjiang** [comment]
the code base has been updated to WDK 10.0.18362.0

**Comment by morizzo** [comment]
Brandon,

Thank you for quick fix but unfortunately nothing seems improved.
NetPacketLibrary.h references lots of NetRing* functions but those functions are not declared in any of header files in _Windows Kits\10\Include\10.0.18362.0\km\netcx_ directory.

Missing functions are:

> NetRingAdvanceEndFragmentIterator
> NetRingAdvanceFragmentIterator
> NetRingAdvancePacketIterator
> NetRingGetAllFragmentIterator
> NetRingGetAllPacketIterator
> NetRingGetTxDrainPacketFragmentIterator
> NetRingGetTxDrainPacketIterator
> NetRingGetTxPostPacketFragmentIterator
> NetRingIteratorAny
> NetRingIteratorGetFragment
> NetRingIteratorGetPacket
> NetRingSetAllFragmentIterator
> NetRingSetAllPacketIterator
> NetRingSetTxDrainFragmentIterator
> NetRingSetTxDrainPacketIterator

Any ideas?

Thanks,
Morizzo

**Comment by brandonjiang** [comment]
Hey, Morizzo

Sorry I missed the NetPacketLibrary.h in my previous commit, now it should be built correctly.

Thanks
Brandon
