### ISSUE TITLE
NCM Driver for Windows Missing Function Definitions

### ISSUE THREAD

**Issue by krkaran12** [Microsoft/NCM-Driver-for-Windows#5]
NetPacketLibrary.h references lots of NetRing* functions but those functions are not declared in any of header files in Windows Kits\10\Include\10.0.18362.0\km\netcx directory.

Missing functions are:

NetRingAdvanceEndFragmentIterator
NetRingAdvanceFragmentIterator
NetRingAdvancePacketIterator
NetRingGetAllFragmentIterator
NetRingGetAllPacketIterator
NetRingGetTxDrainPacketFragmentIterator
NetRingGetTxDrainPacketIterator
NetRingGetTxPostPacketFragmentIterator
NetRingIteratorAny
NetRingIteratorGetFragment
NetRingIteratorGetPacket
NetRingSetAllFragmentIterator
NetRingSetAllPacketIterator
NetRingSetTxDrainFragmentIterator
NetRingSetTxDrainPacketIterator

Any ideas?

**Comment by brandonjiang** [comment]
Hey, the NetPacketLibrary.h has been updated, and it should be built correctly now

Thanks
