### ISSUE TITLE
Is there any popular type-c to ethernet dongle chip supporting usb NCM?

### ISSUE THREAD

**Issue by baybal** [microsoft/NCM-Driver-for-Windows#7]
Is there any popular type-c to ethernet dongle chip supporting usb NCM?

**Comment by brandonjiang** [comment]
I know that Dell D3000 and D6000 dock have Ethernet chip inside that support NCM. I don't have a full list so there may be others that I'm not aware of

**Comment by baybal** [comment]
I found that one rare at this moment chip supports NCM.

RTL8154 2.5GBE , was released last year. Some dongles with it are already on taobao
