### ISSUE TITLE
Is this driver already shipping with Windows 10?

### ISSUE THREAD

**Issue by giuliomoro** [microsoft/NCM-Driver-for-Windows#8]
Hi there,
Is this driver already shipping with Windows 10, or will it ship with it anytime soon?
Thanks

**Comment by brandonjiang** [comment]
Hey,

This driver is officially part of  Windows 11, and it's shipped as a built-in class driver in Windows 11 for all NCM compatible devices 

Thanks

**Comment by rafi16jan** [comment]
@brandonjiang is it possible to build the driver for windows 10 from this source?

**Comment by brandonjiang** [comment]
@rafi16jan , for testing purpose it is possible to built and run the driver for Windows 10 by using the code from release_2004 branch. However, it wouldn't work and be supported in production for Windows 10.

Windows 11 is the first OS officially has built-in NCM support

**Comment by rafi16jan** [comment]
Is "for testing purpose" means we are able to connect to NCM device (like macbook) and have working network connected or it would be something dummy to only tests simple connectivity?

**Comment by brandonjiang** [comment]
"for testing purpose" meaning you won't be able to get WHQL certificate for your driver based on release_2004 branch, and it won't work on Windows 11 or future OS release.

**Comment by rafi16jan** [comment]
I see, so it's just like an unknown publisher driver right? But still works for personal use

**Comment by brandonjiang** [comment]
Yes, you would have to enable [test signing](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/installing-test-signed-driver-packages) to use this driver built by yourself
