### ISSUE TITLE
Windows on ARM, Support?

### ISSUE THREAD

**Issue by sidd-kishan** [microsoft/NCM-Driver-for-Windows#9]
Please let us know when can we have an ARM64 version for Windows on ARM OS. We can help you test we have Windows on Rasberry Pi setup. Please pursue it we at Windows on Rasberry Pi community will be glad to extend support in testing your drivers and tools for ARM64.

**Comment by brandonjiang** [comment]
Hey,

This driver is officially part of Windows 11, and it's fully support on ARM64 version of Windows 11.  

Thanks
